name: Twitter Central Kurdish Dataset PyInstaller

on:
  push:
  workflow_dispatch:
  schedule:
  # 每周日的UTC时间1点执行
  - cron: '0 1 * * 0'

jobs:
  package-windows:
    runs-on: windows-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas
        pip install openpyxl
        pip install pyinstaller
    - name: Fetch latest data
      run: python main.py
    - name: Package script
      run: pyinstaller --onefile main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-windows
        path: dist/main.exe

  package-mac:
    runs-on: macos-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas
        pip install openpyxl
        pip install pyinstaller
    - name: Fetch latest data
      run: python main.py
    - name: Package script
      run: pyinstaller --onefile main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-mac
        path: dist/main
