name: Twitter Central Kurdish Dataset 

on:
  push:
  workflow_dispatch:
  schedule:
  # 每周日的UTC时间1点执行
  - cron: '0 1 * * 0'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas
        pip install openpyxl
    - name: Fetch latest data
      run: python main.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
    - name: Push changes 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}
        force: true
